import { Policyholders } from 'src/entities/policyholders.entity';

export const seed: Policyholders[] = [
  {
    code: '0001',
    name: '保戶1',
    registrationDate: new Date(),
    introducerCode: null,
    parentCode: null,
    isLeftChild: null,
  },
  {
    code: '0002',
    name: '保戶2',
    registrationDate: new Date(),
    introducerCode: '0001',
    parentCode: '0001',
    isLeftChild: true,
  },
  {
    code: '0003',
    name: '保戶3',
    registrationDate: new Date(),
    introducerCode: '0001',
    parentCode: '0001',
    isLeftChild: false,
  },
  {
    code: '0004',
    name: '保戶4',
    registrationDate: new Date(),
    introducerCode: '0001',
    parentCode: '0002',
    isLeftChild: true,
  },
  {
    code: '0005',
    name: '保戶5',
    registrationDate: new Date(),
    introducerCode: '0001',
    parentCode: '0002',
    isLeftChild: false,
  },
  {
    code: '0006',
    name: '保戶6',
    registrationDate: new Date(),
    introducerCode: '0003',
    parentCode: '0003',
    isLeftChild: true,
  },
  {
    code: '0007',
    name: '保戶7',
    registrationDate: new Date(),
    introducerCode: '0003',
    parentCode: '0003',
    isLeftChild: false,
  },
  {
    code: '0008',
    name: '保戶8',
    registrationDate: new Date(),
    introducerCode: '0002',
    parentCode: '0004',
    isLeftChild: true,
  },
  {
    code: '0009',
    name: '保戶9',
    registrationDate: new Date(),
    introducerCode: '0002',
    parentCode: '0004',
    isLeftChild: false,
  },
  {
    code: '0010',
    name: '保戶10',
    registrationDate: new Date(),
    introducerCode: '0002',
    parentCode: '0005',
    isLeftChild: true,
  },
  {
    code: '0011',
    name: '保戶11',
    registrationDate: new Date(),
    introducerCode: '0002',
    parentCode: '0005',
    isLeftChild: false,
  },

  {
    code: '0012',
    name: '保戶12',
    registrationDate: new Date(),
    introducerCode: '0001',
    parentCode: '0006',
    isLeftChild: true,
  },
  {
    code: '0013',
    name: '保戶13',
    registrationDate: new Date(),
    introducerCode: '0006',
    parentCode: '0006',
    isLeftChild: false,
  },
  {
    code: '0014',
    name: '保戶14',
    registrationDate: new Date(),
    introducerCode: '0007',
    parentCode: '0007',
    isLeftChild: true,
  },
  {
    code: '0015',
    name: '保戶15',
    registrationDate: new Date(),
    introducerCode: '0007',
    parentCode: '0007',
    isLeftChild: false,
  },
  {
    code: '0016',
    name: '保戶16',
    registrationDate: new Date(),
    introducerCode: '0001',
    parentCode: '0008',
    isLeftChild: true,
  },
  {
    code: '0017',
    name: '保戶17',
    registrationDate: new Date(),
    introducerCode: '0001',
    parentCode: '0008',
    isLeftChild: false,
  },
];
